import("./8ball");
import("./cat");
import("./chucknorris");
import("./dog");
import("./github");
import("./help");
import("./kebac");
import("./list");
import("./meetup");
import("./owo");
import("./pick");
import("./roll");
import("./sl");
import("./soundboard");
import("./surun");
import("./top");
import("./tts");
import("./xkcd");
import("./youtube");
import("./zalgo");

export {};
